version: '3.8'

services:
  licensingservice:
    image: mariamihai/sma-licensing-service:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: "local"
    networks:
      backend:
        aliases:
            - "licensingservice"
networks:
  backend:
    driver: bridge