name: organization-service

on:
  # Trigger analysis when pushing in master or pull requests, and when creating a pull request.
  push:
    branches:
      - master
    paths:
      - "organization-service/**"

jobs:
  Steps:
    name: Steps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build the package
        run: |
          cd organization-service
          mvn -B package

      - name: Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ORGANIZATION_SERVICE }}
        run: |
          cd organization-service
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sma-organization-service

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username:  ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd organization-service
          mvn dockerfile:build
          mvn dockerfile:tag@tag-version -Drevision=${GITHUB_RUN_NUMBER}
          mvn dockerfile:push@push-latest
          mvn dockerfile:push@push-version -Drevision=${GITHUB_RUN_NUMBER}